<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Cancel' => 'Отменить',
  'Create' => 'Создать ',
  'Data' => 'Данные ',
  'Delete' => 'Удалить ',
  'Do you want to delete this item?' => 'Вы действительно хотите удалить?',
  'Fields with <span class="required">*</span> are required.' => 'Поля с <span class="required">*</span> обязательны для заполнения.',
  'Invalid request. Please do not repeat this request again.' => 'Неверный запрос. Пожалуйста, не повторяйте этот запрос снова.',
  'Manage' => 'Управлять',
  'Relations' => 'Отношения',
  'Save' => 'Сохранить',
  'Search' => 'Поиск',
  'Stfa' => '',
  'Stfa Authitem' => '',
  'Stfa Flow Access' => '',
  'Stfa Flow Accesses' => '',
  'Stfa Notes' => '',
  'Stfa Stsf' => '',
  'StfaAuthitem' => '',
  'StfaStsf' => '',
  'Stfl' => '',
  'Stfl Field' => 'Поле таблицы базы данных',
  'Stfl Flow' => 'График для статуса',
  'Stfl Flows' => 'График для статусов',
  'Stfl Name' => 'Название',
  'Stfl Notes' => 'Комментарии',
  'Stfl Table' => 'Таблица БД',
  'Stlg' => '',
  'Stlg Datetime' => '',
  'Stlg Log' => '',
  'Stlg Logs' => '',
  'Stlg Record' => '',
  'Stlg Stfl' => '',
  'Stlg Stst' => '',
  'Stlg User' => '',
  'StlgStfl' => '',
  'StlgStst' => '',
  'StlgUser' => '',
  'Stsf' => '',
  'Stsf Next Stst' => 'Следующий статус',
  'Stsf Notes' => 'Комментарии',
  'Stsf Prev Stst' => 'Статус в начале',
  'Stsf States Flow' => 'Порядок статусов',
  'Stsf States Flows' => 'Порядок статусов',
  'Stsf Stfl' => 'График статуса',
  'StsfNextStst' => 'Следующий статус',
  'StsfPrevStst' => 'Предыдущий статус',
  'StsfStfl' => 'График статусов',
  'Stst' => 'stst_id',
  'Stst Code' => 'Код',
  'Stst Icon' => 'Иконка',
  'Stst Name' => 'Название',
  'Stst State' => 'График статуса',
  'Stst States' => 'Графики статусов',
  'The requested page does not exist.' => 'Запрошенная страница не существует.',
  'Update' => 'Редактировать',
  'View' => 'Открыть',
  'help.stfa_notes' => '',
  'help.stfl_field' => '',
  'help.stfl_name' => '',
  'help.stfl_notes' => '',
  'help.stfl_table' => '',
  'help.stlg_datetime' => '',
  'help.stlg_record_id' => '',
  'help.stsf_notes' => '',
  'help.stst_code' => '',
  'help.stst_icon' => '',
  'help.stst_name' => '',
);
