<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Cancel' => '',
  'Create' => '',
  'Data' => '',
  'Delete' => '',
  'Do you want to delete this item?' => '',
  'Fields with <span class="required">*</span> are required.' => '',
  'Invalid request. Please do not repeat this request again.' => '',
  'Manage' => '',
  'Relations' => '',
  'Save' => '',
  'Search' => '',
  'Stfa' => '',
  'Stfa Authitem' => '',
  'Stfa Flow Access' => '',
  'Stfa Flow Accesses' => '',
  'Stfa Notes' => '',
  'Stfa Stsf' => '',
  'StfaAuthitem' => '',
  'StfaStsf' => '',
  'Stfl' => '',
  'Stfl Field' => 'DB field',
  'Stfl Flow' => 'Statusu graph',
  'Stfl Flows' => 'Status graphs',
  'Stfl Name' => 'Name',
  'Stfl Notes' => 'Notes',
  'Stfl Table' => 'DB table',
  'Stlg' => '',
  'Stlg Datetime' => '',
  'Stlg Log' => '',
  'Stlg Logs' => '',
  'Stlg Record' => '',
  'Stlg Stfl' => '',
  'Stlg Stst' => '',
  'Stlg User' => '',
  'StlgStfl' => '',
  'StlgStst' => '',
  'StlgUser' => '',
  'Stsf' => '',
  'Stsf Next Stst' => 'Next status',
  'Stsf Notes' => 'Notes',
  'Stsf Prev Stst' => 'Start status',
  'Stsf States Flow' => 'Status sequence',
  'Stsf States Flows' => 'Status sequences',
  'Stsf Stfl' => 'Status graph',
  'StsfNextStst' => 'Next status',
  'StsfPrevStst' => 'Previous status',
  'StsfStfl' => 'Status graph',
  'Stst' => '',
  'Stst Code' => 'Code',
  'Stst Icon' => 'Icon',
  'Stst Name' => 'Name',
  'Stst State' => 'Status graph',
  'Stst States' => 'Status graphs',
  'The requested page does not exist.' => '',
  'Update' => '',
  'View' => '',
  'help.stfa_notes' => '',
  'help.stfl_field' => '',
  'help.stfl_name' => '',
  'help.stfl_notes' => '',
  'help.stfl_table' => '',
  'help.stlg_datetime' => '',
  'help.stlg_record_id' => '',
  'help.stsf_notes' => '',
  'help.stst_code' => '',
  'help.stst_icon' => '',
  'help.stst_name' => '',
);
