<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Cancel' => 'Atcelt',
  'Create' => 'Izveidot',
  'Data' => 'Dati',
  'Delete' => 'Dzēst',
  'Do you want to delete this item?' => 'Vai patiešam jūs vēlaties dzēst šo ierakstu?',
  'Fields with <span class="required">*</span> are required.' => 'Ievadlauki ar <span class="required">*</span> ir obligāti.',
  'Invalid request. Please do not repeat this request again.' => 'Kļūdains pieprasījums',
  'Manage' => 'Saraksts',
  'Name' => 'Vārds',
  'Relations' => 'Saistītās tabulas',
  'Save' => 'Saglabāt',
  'Search' => 'Meklēt',
  'Stfa' => '',
  'Stfa Authitem' => '',
  'Stfa Flow Access' => '',
  'Stfa Flow Accesses' => '',
  'Stfa Notes' => '',
  'Stfa Stsf' => '',
  'StfaAuthitem' => '',
  'StfaStsf' => '',
  'Stfl' => 'stfl_id',
  'Stfl Field' => 'DB tabulas lauks',
  'Stfl Flow' => 'Statusu grafs',
  'Stfl Flows' => 'Statusu grafi',
  'Stfl Name' => 'Nosaukums',
  'Stfl Notes' => 'Piezīmes',
  'Stfl Table' => 'DB tabula',
  'Stlg' => '',
  'Stlg Datetime' => '',
  'Stlg Log' => '',
  'Stlg Logs' => '',
  'Stlg Record' => '',
  'Stlg Stfl' => '',
  'Stlg Stst' => '',
  'Stlg User' => '',
  'StlgStfl' => '',
  'StlgStst' => '',
  'StlgUser' => '',
  'Stsf' => 'stsf_id',
  'Stsf Next Stst' => 'Nākošais statuss',
  'Stsf Notes' => 'Piezīmes',
  'Stsf Prev Stst' => 'Sākumstatuss',
  'Stsf States Flow' => 'Statusu secība',
  'Stsf States Flows' => 'Statusu secības',
  'Stsf Stfl' => 'Statusu grafs',
  'StsfNextStst' => 'Nākošais statuss',
  'StsfPrevStst' => 'Iepriekšējais statuss',
  'StsfStfl' => 'Statusu grafs',
  'Stst' => 'stst_id',
  'Stst Code' => 'Kods',
  'Stst Icon' => 'Ikona',
  'Stst Name' => 'Nosaukums',
  'Stst State' => 'Statusu grafs',
  'Stst States' => 'Statusu grafi',
  'The requested page does not exist.' => 'Pieprasītā lapa neeksistē',
  'Update' => 'Labot',
  'View' => 'Skatīt',
  'help.stfa_notes' => '',
  'help.stfl_field' => '',
  'help.stfl_name' => '',
  'help.stfl_notes' => '',
  'help.stfl_table' => '',
  'help.stlg_datetime' => '',
  'help.stlg_record_id' => '',
  'help.stsf_notes' => '',
  'help.stst_code' => '',
  'help.stst_icon' => '',
  'help.stst_name' => '',
);
