<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Fields with <span class="required">*</span> are required.' => 'Ievadlauki, kas atzīmēti ar <span class="required">*</span>, ir obligāti.',
  'Invalid request. Please do not repeat this request again.' => 'Kļūdains pieprasījums. Lūdzu neatkārtot to.',
  'help.ccmp_statuss' => '',
  'help.ccmp_vat_registrtion_no' => '',
  'help.ccnt_code' => '',
  'help.ccnt_name' => '',
  'ccmpCompanies - CcmpCompany' => '@@Valsts@@',
  'Cancel' => 'Atcelt',
  'Ccmp' => 'ccmp_id',
  'Ccmp Ccnt' => 'Valsts',
  'Ccmp Companies' => 'Uzņēmumi',
  'Ccmp Company' => 'Uzņemums',
  'Ccmp Description' => 'Piezīmes',
  'Ccmp Name' => 'Nosaukums',
  'Ccmp Official Address' => 'Juridiskā adrese',
  'Ccmp Registration Address' => 'Reg adrese',
  'Ccmp Registrtion No' => 'Reģistrācijas nummurs',
  'Ccmp Statuss' => 'Statuss',
  'Ccmp Vat Registrtion No' => 'PVN maksātaja nummurs',
  'CcmpCcnt' => 'Valsts',
  'Ccnt' => 'ccnt_id',
  'Ccnt Code' => 'Valsts kods',
  'Ccnt Countries' => 'Valstis',
  'Ccnt Country' => 'Valsts nosaukums',
  'Ccnt Name' => 'Nosaukums',
  'Create' => 'Izveidot',
  'Data' => 'Dati',
  'Delete' => 'Dzēst',
  'Do you want to delete this item?' => 'Vai pa tiešām vēlaties dzēst šo ierakstu',
  'Manage' => 'Saraksts',
  'Relations' => 'Saistītās tabulas',
  'Save' => 'Saglabāt',
  'Search' => 'Meklēt',
  'The requested page does not exist.' => 'Pieprasītā lapa neeksistē',
  'Update' => 'Labot',
  'View' => 'Skatīt',
  'ccmpCcnt - CcntCountry' => 'Valsts',
  'help.ccmp_description' => 'Paredzets piezīmēm par uzņemumu',
  'help.ccmp_name' => 'Jāievada uzņemuma nosaukums',
  'help.ccmp_official_address' => ' Jāuzrāda oficiālā adrese',
  'help.ccmp_registration_address' => 'Jāuzrāda uzņēmuma reģistrētā adrese',
  'help.ccmp_registrtion_no' => 'Jāievada uzņemuma reģistrācijas numurs',
  '{class_name} <small>Create</small>' => '<small>Izveidot</small> {class_name}',
);
